name: ramclustr-test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base >=4.1
  - r-devtools
  - r-dynamictreecut
  - r-fastcluster
  - r-gplots
  - r-ggplot2
  - bioconductor-msnbase
  - bioconductor-xcms
  - r-curl
  - r-webchem
  - r-stringi
  - r-jsonlite
  - r-stringr
  - r-xml2
  - r-e1071
  - r-interpretmsspectrum >=1.3.8
  - r-testthat
  - r-readxl
  - r-rentrez
  - r-covr
  - r-patrick
