Experiment<-"ramclustR_smallset_test"
chrominst<-"Waters UPLC: C18 ACN Gradient"
msinst<-"Waters Xevo G2 TOF"
CE1<-"6"
CE2<-"15-30"
mstype<-"Q-TOF"
msmode<-"P"
ionization<-"ESI"
colgas<-"Ar"
msscanrange<-"50-1200"
conevolt<-"30"

