# This is a basic workflow to help you get started with Actions
name: R Conda (with codecov)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, dev, release_1.3.x]
  pull_request:
    branches: [ master, dev, release_1.3.x ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false      
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: conda/environment-test.yaml
      - run: |
          conda init bash
          conda env list

      - name: Test coverage
        run: |
          conda activate test
          Rscript -e "covr::codecov(quiet = FALSE)"
